#!/bin/bash

if git status
    then
        echo -e "\033[97m\033[42mСтатус успешно выведен, запускаю скрипт\033[0m"
        sleep 5
        git add .
        git commit -m "⚙️ обновление через скрипт"
            if git push
                then
                    sleep 3
                    echo -e "\033[97m\033[42mУспешное обновление\033[0m"
            fi
    else
        echo -e "\033[91m\033[107mИзменений не найдено!\033[0m"
fi
